language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cs4p/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cs4p/docker-react npm run test -- --coverage